### PR TITLE
Change previews from links to images

### PR DESCRIPTION
**Pull request by birjj**
Making it much easier to get a quick overview (instead of having to open each and every preview separately).

Also changed to relative links because best practices and such.

### CODE REVIEW

**Comment by dkeg** [comment]
That's a fair request. Actually used to be that way, but since all the previews are not uniform, it started to bug me.

**Comment by birjj** [comment]
Updated previews using [this js script](https://jsfiddle.net/yfxzkay0/). _Could_ probably convert it to a bash script so it can be ran automatically, but that'd take too long for me to be bothered.

Honestly not sure I like this new version more, but now they're all consistent at least.

**Comment by dkeg** [comment]
Dude, you are the man! Thank you! At first I hadn't realized you were actually submitting the request. Call it a momentary lapse : )
I thought you were using as a platform to make the suggestion. 
I really appreciate it. Really cool of you to help me out. I appreiciate it very much.

**Comment by birjj** [comment]
Cheers! Probably should've made it "change_d_" in the title to avoid confusion

On a sidenote, I really liked the scrots you added before my merge. If you still have them, I'd suggest readding them (even if they aren't on every theme)

**Pull request merged**
